// All collection IDs verified from Swiggy network tab (Bangalore — lat=12.97530, lng=77.59100)
export const CATEGORIES = [
  { emoji: '🍕', label: 'Pizza',        slug: 'pizza',        collection: '83631', tags: 'layout_CCS_Pizza',              color: ['#FF6B35', '#F7443E'] },
  { emoji: '🍗', label: 'Biryani',      slug: 'biryani',      collection: '83639', tags: 'layout_CCS_Biryani',            color: ['#F7B731', '#F0932B'] },
  { emoji: '🍛', label: 'South Indian', slug: 'south-indian', collection: '83634', tags: 'layout_CCS_SouthIndian',        color: ['#20BF6B', '#0FB9B1'] },
  { emoji: '🥞', label: 'Dosa',         slug: 'dosa',         collection: '80424', tags: 'layout_CCS_Dosa',               color: ['#F7971E', '#FFD200'] },
  { emoji: '🍔', label: 'Burgers',      slug: 'burgers',      collection: '83637', tags: 'layout_CCS_Burger',             color: ['#FF416C', '#FF4B2B'] },
  { emoji: '🥡', label: 'Chinese',      slug: 'chinese',      collection: '83636', tags: 'layout_CCS_Chinese',            color: ['#c94b4b', '#4b134f'] },
  { emoji: '🌯', label: 'Rolls',        slug: 'rolls',        collection: '83669', tags: 'layout_CCS_Rolls',              color: ['#A18CD1', '#FBC2EB'] },
  { emoji: '🍰', label: 'Desserts',     slug: 'desserts',     collection: '83661', tags: 'layout_CCS_Desserts',           color: ['#FD79A8', '#D63031'] },
  { emoji: '🥟', label: 'Momos',        slug: 'momos',        collection: '80461', tags: 'layout_CCS_Momos',              color: ['#4facfe', '#00f2fe'] },
  { emoji: '🥗', label: 'Salad',        slug: 'salad',        collection: '80394', tags: 'layout_CCS_Salad',              color: ['#43E97B', '#38F9D7'] },
  { emoji: '🎂', label: 'Cakes',        slug: 'cakes',        collection: '83655', tags: 'layout_CCS_Cake',               color: ['#f093fb', '#f5576c'] },
  { emoji: '🍚', label: 'Idli',         slug: 'idli',         collection: '80440', tags: 'layout_CCS_Idli',               color: ['#FDDB92', '#D1FDFF'] },
  { emoji: '🍜', label: 'Noodles',      slug: 'noodles',      collection: '80463', tags: 'layout_ux4',                    color: ['#f7971e', '#ffd200'] },
  { emoji: '🥙', label: 'Shawarma',     slug: 'shawarma',     collection: '80402', tags: 'layout_Shawarma_Contextual',    color: ['#c79081', '#dfa579'] },
  { emoji: '🍝', label: 'Pasta',        slug: 'pasta',        collection: '80479', tags: 'layout_CCS_Pasta',              color: ['#f953c6', '#b91d73'] },
  { emoji: '🥤', label: 'Shakes',       slug: 'shakes',       collection: '83673', tags: 'layout_CCS_Shakes',             color: ['#4776E6', '#8E54E9'] },
  { emoji: '🥐', label: 'Samosa',       slug: 'samosa',       collection: '80396', tags: '',                              color: ['#F2994A', '#F2C94C'] },
  { emoji: '☕', label: 'Coffee',       slug: 'coffee',       collection: '83907', tags: 'layout_CCS_Coffee',             color: ['#6F4E37', '#C9A96E'] },
  { emoji: '🧁', label: 'Pastry',       slug: 'pastry',       collection: '80355', tags: 'layout_ux4',                    color: ['#FC5C7D', '#6A82FB'] },
  { emoji: '🍹', label: 'Juices',       slug: 'juices',       collection: '80445', tags: 'layout_Juices_Contextual',      color: ['#56AB2F', '#A8E063'] },
]
