// All collection IDs verified from Swiggy network tab (Bangalore — lat=12.97530, lng=77.59100)
export const CATEGORIES = [
  { emoji: '🍕', label: 'Pizza',        slug: 'pizza',        collection: '83631', tags: 'layout_CCS_Pizza' },
  { emoji: '🍗', label: 'Biryani',      slug: 'biryani',      collection: '83639', tags: 'layout_CCS_Biryani' },
  { emoji: '🍛', label: 'South Indian', slug: 'south-indian', collection: '83634', tags: 'layout_CCS_SouthIndian' },
  { emoji: '🥞', label: 'Dosa',         slug: 'dosa',         collection: '80424', tags: 'layout_CCS_Dosa' },
  { emoji: '🍔', label: 'Burgers',      slug: 'burgers',      collection: '83637', tags: 'layout_CCS_Burger' },
  { emoji: '🥡', label: 'Chinese',      slug: 'chinese',      collection: '83636', tags: 'layout_CCS_Chinese' },
  { emoji: '🌯', label: 'Rolls',        slug: 'rolls',        collection: '83669', tags: 'layout_CCS_Rolls' },
  { emoji: '🍰', label: 'Desserts',     slug: 'desserts',     collection: '83661', tags: 'layout_CCS_Desserts' },
  { emoji: '🥟', label: 'Momos',        slug: 'momos',        collection: '80461', tags: 'layout_CCS_Momos' },
  { emoji: '🥗', label: 'Salad',        slug: 'salad',        collection: '80394', tags: 'layout_CCS_Salad' },
  { emoji: '🎂', label: 'Cakes',        slug: 'cakes',        collection: '83655', tags: 'layout_CCS_Cake' },
  { emoji: '🍚', label: 'Idli',         slug: 'idli',         collection: '80440', tags: 'layout_CCS_Idli' },
  { emoji: '🍜', label: 'Noodles',      slug: 'noodles',      collection: '80463', tags: 'layout_ux4' },
  { emoji: '🥙', label: 'Shawarma',     slug: 'shawarma',     collection: '80402', tags: 'layout_Shawarma_Contextual' },
  { emoji: '🍝', label: 'Pasta',        slug: 'pasta',        collection: '80479', tags: 'layout_CCS_Pasta' },
  { emoji: '🥤', label: 'Shakes',       slug: 'shakes',       collection: '83673', tags: 'layout_CCS_Shakes' },
  { emoji: '🥐', label: 'Samosa',       slug: 'samosa',       collection: '80396', tags: '' },
  { emoji: '☕', label: 'Coffee',       slug: 'coffee',       collection: '83907', tags: 'layout_CCS_Coffee' },
  { emoji: '🧁', label: 'Pastry',       slug: 'pastry',       collection: '80355', tags: 'layout_ux4' },
  { emoji: '🍹', label: 'Juices',       slug: 'juices',       collection: '80445', tags: 'layout_Juices_Contextual' },
]
